print('What do you get when you cross a snowman with a vampire?')
input()
print('Frostbite!')
print()
print('What does a dentist call an astronaut\'s cavity?')
input()
print('A black hole!')
print('Knock knock.')
input()
print("Who's there?")
input()
print('Interrupting cow.')
input()
print('interruptng cow wh', end='')
print('-Moo!')
